---
- name: "Apache installation using docker"
  hosts: prod
  become: true
  vars_files:
    - files/secrets/credentials.yml
  pre_tasks:
    - name: Install some package
      package: name='{{ item }}' state=present
      when: ansible_distribution == "CentOS"
      loop:
        - epel-release
        - wget
        - git
    - name: Install python-pip
      yum: name=python3-pip state=present update_cache=yes
    - name: Install docker python
      pip: name=docker-py
  tasks:
    - name: Copy website file template
      template:
        src: index.html.j2
        dest: /home/admin/index.html
    - name: Create apache container
      docker_container:
        name: webapp
        image: httpd
        ports:
          - "8081:80"
        volumes:
          /home/admin/index.html:/usr/local/apache2/htdocs/index.html
    
